# Generated by Django 4.2.2 on 2023-08-10 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_item_reservation_timer'),
        ('users', '0002_appuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='managed_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.store'),
        ),
    ]
