# Generated by Django 4.2.2 on 2023-07-19 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20, unique=True)),
                ('car_type', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Customer Cars',
            },
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrance_date', models.DateTimeField(auto_now_add=True)),
                ('exit_date', models.DateTimeField(blank=True, null=True)),
                ('license_plate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parking.customercar')),
            ],
            options={
                'verbose_name_plural': 'Parking',
            },
        ),
    ]
