# Generated by Django 4.2.2 on 2023-08-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercar',
            name='car_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
