# Generated by Django 4.2.2 on 2023-08-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_alter_customercar_car_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='non_registered_code',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
