# Generated by Django 4.2.2 on 2023-08-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_parking_non_registered_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='license_plate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
