# Generated by Django 4.2.2 on 2023-08-11 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_alter_parking_license_plate'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='customer_car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parking.customercar'),
        ),
    ]
