# Generated by Django 4.2.2 on 2023-08-11 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_parking_customer_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customercar',
            name='car_type',
        ),
    ]
