version: '3.8'

services:
  web:
    image: for_deploy
    build: .
    command: gunicorn --bind=0.0.0.0:8000 mall_app.wsgi:application
    volumes:
      - .:/usr/scr/mall_app
    ports:
      - "8000:8000"
    env_file:
      - /mall_app/.env
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: mall_db
      POSTGRES_USER: adminuser542
      POSTGRES_PASSWORD: Hhjypb8rKIUZMSd
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgresql:/var/lib/postgresql/data
  nginx:
    image: nginx
    ports:
      - 81:80
      - 443:443
    volumes:
      - ./staticfiles:/home/app/web/staticfiles
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/logs/nginx
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    links:
      - web