version: '3.8'

services:
  web:
    image: for_deploy
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/scr/mall_app
    ports:
      - "8000:8000"
    env_file:
      - /.env
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: mall_db
      POSTGRES_USER: adminuser542
      POSTGRES_PASSWORD: Hhjypb8rKIUZMSd
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgresql:/var/lib/postgresql/data
