# Generated by Django 4.2.2 on 2023-08-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_item_image_item_quantity_store_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_claimed',
            field=models.BooleanField(default=False),
        ),
    ]
