# Generated by Django 4.2.2 on 2023-08-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_reservation_is_claimed'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='item_quantity_increased',
            field=models.BooleanField(default=False),
        ),
    ]
