# Generated by Django 4.2.2 on 2023-08-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_reservation_item_quantity_increased'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='reservation_timer',
            field=models.PositiveIntegerField(default=5, help_text='Reservation time in minutes'),
        ),
    ]
