# Generated by Django 4.2.2 on 2023-08-12 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_store_email_store_location_store_phone_store_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='working_hours',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
