# Generated by Django 4.2.2 on 2023-08-12 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_store_working_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='working_hours',
            field=models.CharField(blank=True, default='10.00-22.00', max_length=200, null=True),
        ),
    ]
