# Generated by Django 4.2.2 on 2023-07-19 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cinema', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='screening',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.schedule'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.hallseat'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.cinemahall'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.movie'),
        ),
        migrations.AddField(
            model_name='movie',
            name='halls',
            field=models.ManyToManyField(to='cinema.cinemahall'),
        ),
        migrations.AddField(
            model_name='hallseat',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.cinemahall'),
        ),
        migrations.AddField(
            model_name='hallseat',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='hallseat',
            unique_together={('hall', 'row', 'column')},
        ),
    ]
