# Generated by Django 4.2.2 on 2023-07-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='halls',
            field=models.ManyToManyField(to='cinema.cinemahall'),
        ),
    ]
