# Generated by Django 4.2.2 on 2023-08-12 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_movie_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hallseat',
            unique_together={('row', 'column', 'hall')},
        ),
    ]
